### ISSUE TITLE
How to change the generation length

### ISSUE THREAD

**Issue by ujjawal-ti** [stanfordnlp/dspy#590]
Hey,
I'm initializing my LM as follows,

```
extras={'max_tokens':4000,'temperature':0.7}
vllm = dspy.HFClientVLLM(model="Mistral-7B-Instruct-v0.1",url="https://my_vllm_url/api",kwargs=extras)
dspy.settings.configure(lm=vllm)
```
But the response length is still short.
I have not provided any such `desc` in  `dspy.OutputField()` too.

Any idea why am I facing this ?

**Comment by arnavsinghvi11** [comment]
Hi @ujjawal-ti , this is fairly dependent on what your task is and how your current DSPy setup handles that. Feel free to share as needed. 
Also, setting the desc to specify some range of response length can actually help too.

**Comment by thomasahle** [comment]
You should be able to use `min_length=...`
```python
class Foo(BaseModel):
    short: str = Field(min_length=3)
    long: str = Field(max_length=10)
    regex: str = Field(pattern=r'^\d*$')  
```
https://docs.pydantic.dev/dev/concepts/fields/

Just be sure you use typed dspy: https://github.com/stanfordnlp/dspy?tab=readme-ov-file#5-pydantic-types

**Comment by ujjawal-ti** [comment]
Thanks @thomasahle @arnavsinghvi11

**Comment by hingkan** [comment]
Hi,  have you solved this problem. When I try to use the following code, the generated length is still very short.
`dspy.OutputField(desc="", min_length=1024, max_length=4096)`

Looking forward to your reply.

**Comment by thomasahle** [comment]
What does your code look like?

**Comment by hingkan** [comment]
> You forgot to use typed dspy.
> 
> https://github.com/stanfordnlp/dspy?tab=readme-ov-file#5-pydantic-types
> 
> Replace dspy.ChainOfThought with dspy.TypedChainOfThought

The problem persists when I replace ChainOfThought with TypedChainOfThought.
**code:**
`TypedChainOfThought(WriteLongArticle)`
**result**
![dspy_result](https://github.com/stanfordnlp/dspy/assets/46413333/824ef73c-b162-48f6-b435-6d7d7d90242c)


It still doesn't seem to be limited to min length and max length

**Comment by thomasahle** [comment]
It looks like you're running out of output tokens. Note how the text stops in the middle of a sentence.

**Comment by hingkan** [comment]
> It looks like you're running out of output tokens. Note how the text stops in the middle of a sentence.

**code:**
`turbo = dspy.HFClientVLLM(model='llama2-6b',
                          port=8000,
                          url="http://localhost",
                          max_tokens=1024*8,
                          temperature=0.8,
                          top_p=0.8)

dspy.settings.configure(lm=turbo)`

I set up the model max_tokens=1024*8, but it doesn't seem to be working.

![dspy_vllm](https://github.com/stanfordnlp/dspy/assets/46413333/11043016-d686-4b27-9b7a-c3cba473a616)

The max_tokens parameter in the HFClientVLLM class seems useless because _generate() cannot get max_tokens.Is there a way to improve, or is there a way to pass max_tokens to _generate() before making model predictions.

Looking forward to your reply.

**Comment by hingkan** [comment]
> > It looks like you're running out of output tokens. Note how the text stops in the middle of a sentence.
> 
> **code:** `turbo = dspy.HFClientVLLM(model='llama2-6b', port=8000, url="http://localhost", max_tokens=1024*8, temperature=0.8, top_p=0.8)
> 
> dspy.settings.configure(lm=turbo)`
> 
> I set up the model max_tokens=1024*8, but it doesn't seem to be working.
> 
> ![dspy_vllm](https://private-user-images.githubusercontent.com/46413333/320743227-11043016-d686-4b27-9b7a-c3cba473a616.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDUyNDIsIm5iZiI6MTcxMjY0NDk0MiwicGF0aCI6Ii80NjQxMzMzMy8zMjA3NDMyMjctMTEwNDMwMTYtZDY4Ni00YjI3LTliN2EtYzNjYmE0NzNhNjE2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzM1ZTljODNlZTI4ZjI0NjY1MzVlZDk0MDM5MjJmOGY1MDRmNGFjOTJkM2JlMjIxM2E1MDFjMDkyMzY3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ozO7qERH3hKWq9SSJaznfbHJsoDLJHt01W4WdTRSlQ)
> 
> The max_tokens parameter in the HFClientVLLM class seems useless because _generate() cannot get max_tokens.Is there a way to improve, or is there a way to pass max_tokens to _generate() before making model predictions.
> 
> Looking forward to your reply.

Sorry, I just noticed "kwargs = {**self.kwargs, **kwargs}". Amazingly, max tokens may not be set up successfully.

**Comment by hingkan** [comment]
> > > It looks like you're running out of output tokens. Note how the text stops in the middle of a sentence.
> > 
> > 
> > **code:** `turbo = dspy.HFClientVLLM(model='llama2-6b', port=8000, url="http://localhost", max_tokens=1024*8, temperature=0.8, top_p=0.8)
> > dspy.settings.configure(lm=turbo)`
> > I set up the model max_tokens=1024*8, but it doesn't seem to be working.
> > ![dspy_vllm](https://private-user-images.githubusercontent.com/46413333/320743227-11043016-d686-4b27-9b7a-c3cba473a616.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDUyNDIsIm5iZiI6MTcxMjY0NDk0MiwicGF0aCI6Ii80NjQxMzMzMy8zMjA3NDMyMjctMTEwNDMwMTYtZDY4Ni00YjI3LTliN2EtYzNjYmE0NzNhNjE2LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzM1ZTljODNlZTI4ZjI0NjY1MzVlZDk0MDM5MjJmOGY1MDRmNGFjOTJkM2JlMjIxM2E1MDFjMDkyMzY3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ozO7qERH3hKWq9SSJaznfbHJsoDLJHt01W4WdTRSlQ)
> > The max_tokens parameter in the HFClientVLLM class seems useless because _generate() cannot get max_tokens.Is there a way to improve, or is there a way to pass max_tokens to _generate() before making model predictions.
> > Looking forward to your reply.
> 
> Sorry, I just noticed "kwargs = {**self.kwargs, **kwargs}". Amazingly, max tokens may not be set up successfully.

Thanks. HFClientVLLM does not pass kwargs to its parent class HFModel, and HFModel does not pass kwargs to its parent class LM. Finally, the default value LM is used.

![1](https://github.com/stanfordnlp/dspy/assets/46413333/777e0a96-84d3-47ae-87f1-a9f8fcffa61a)
![2](https://github.com/stanfordnlp/dspy/assets/46413333/5e1dfea3-9309-460b-9c11-16c4097d41d7)
![3](https://github.com/stanfordnlp/dspy/assets/46413333/dfc8006d-6ff4-411d-895d-6a75a72fe181)

It has been solved. Thank you for your time to reply!

**Comment by leocnj** [comment]
@hingkan I am using dspy `0.4.9` version now. It seems that the issue still exists. Any work-around to use a large `max_tokens` ?
